name: Deploy to Workshop

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      
      - uses: wiremod/gmod-upload@master
        with:
          id: 3140746840
          changelog: "Deployment via Github to commit ${GITHUB_SHA:0:7}"
        env:
          STEAM_USERNAME: ${{ secrets.PUBLISH_WORKSHOP_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.PUBLISH_WORKSHOP_PASSWORD }}
